<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Camera properties -->
  <xacro:property name="camera_length" value="0.01" />
  <xacro:property name="camera_width" value="0.1" />
  <xacro:property name="camera_height" value="0.05" />

  <!-- Define base size if used in origin -->
  <xacro:property name="base_length" value="0.5" />
  <xacro:property name="base_height" value="0.2" />

  <!-- Camera Link -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
    </collision>
    <!-- Inertia macro must be defined or imported in your xacro file -->
    <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}" xyz="0 0 0" rpy="0 0 0"/>
  </link>

  <!-- Fixed Joint to base -->
  <joint name="base_camera_link" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${(base_length + camera_length) / 2} 0 ${base_height}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo sensor plugin -->
  <gazebo reference="camera_link">
    <sensor name="camera_sensor" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10.0</update_rate>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>

<!-- 
Gazebo camera and open cv ke liye lec 79 check kar  will be delete after 2025 end-->